[build]
  command = "npm run build"
  publish = "build"  # CRA outputs to the 'build' folder

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"  # Optional: specify Node version if needed
